trigger:
        - master
pool:
        vmImage: 'Ubuntu 18.04'     
variables:
        imageName: 'sti_filas_back'    
        DOCKER_BUILDKIT: 1    
steps:
        - task: Docker@2
          displayName: Construir a imagem do app
          inputs:
                repository: 'theosato/sti_filas_back'
                command: 'buildAndPush'
                Dockerfile: Dockerfile
                containerRegistry: 'dockerHub'
